import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import HomePage from "@/components/HomePage";
import styles from "@/styles/Home.module.css";
import { useAccount } from "wagmi";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ash Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
}
